version: 1.2
workflows:
  - name: DownsampleSam
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/DownsampleSam.wdl
  - name: CollectHsMetrics
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/CollectHsMetrics.wdl
  - name: SimpleSNPChecker
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/SimpleSNPChecker.wdl
  - name: DragenCytosineReportToBismark
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/DragenCytosineReportToBismark.wdl
  - name: CollectDuplexSeqMetricsSplitHumanAndHPV
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/CollectDuplexSeqMetricsSplitHumanAndHPV.wdl
  - name: SamtoolsBedcov
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/SamtoolsBedcov.wdl
  - name: GetHPV16MeanTargetCoverage
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/GetHPV16MeanTargetCoverage.wdl
  - name: GetGAPDHMeanTargetCoverage
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/GetGAPDHMeanTargetCoverage.wdl